FROM centos:8
RUN yum update -y && yum install -y \
  autoconf \
  bison \
  flex \
  gcc-c++ \
  git \
  perl-version \
  perl-Time-HiRes \
  rsync \
  rpm-build \
  make \
  python3
WORKDIR /usr/src/app
